<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net8.0-android</TargetFrameworks>
		<!--<TargetFrameworks Condition="$([MSBuild]::IsOSPlatform('windows'))">$(TargetFrameworks);net8.0-windows10.0.19041.0</TargetFrameworks>-->
		<!--<TargetFrameworks>net8.0-android;net8.0-ios;net8.0-maccatalyst</TargetFrameworks>
		<TargetFrameworks Condition="$([MSBuild]::IsOSPlatform('windows'))">$(TargetFrameworks);net8.0-windows10.0.19041.0</TargetFrameworks>-->
		<!-- Uncomment to also build the tizen app. You will need to install tizen by following this: https://github.com/Samsung/Tizen.NET -->
		<!-- <TargetFrameworks>$(TargetFrameworks);net8.0-tizen</TargetFrameworks> -->

		<!-- Note for MacCatalyst:
		The default runtime is maccatalyst-x64, except in Release config, in which case the default is maccatalyst-x64;maccatalyst-arm64.
		When specifying both architectures, use the plural <RuntimeIdentifiers> instead of the singular <RuntimeIdentifier>.
		The Mac App Store will NOT accept apps with ONLY maccatalyst-arm64 indicated;
		either BOTH runtimes must be indicated or ONLY macatalyst-x64. -->
		<!-- For example: <RuntimeIdentifiers>maccatalyst-x64;maccatalyst-arm64</RuntimeIdentifiers> -->

		<OutputType>Exe</OutputType>
		<RootNamespace>BlissApp</RootNamespace>
		<UseMaui>true</UseMaui>
		<SingleProject>true</SingleProject>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>

		<!-- Display name -->
		<ApplicationTitle>BlissApp</ApplicationTitle>

		<!-- App Identifier -->
		<ApplicationId>com.companyname.blissapp</ApplicationId>

		<!-- Versions -->
		<ApplicationDisplayVersion>1.0</ApplicationDisplayVersion>
		<ApplicationVersion>1</ApplicationVersion>

		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'ios'">11.0</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'maccatalyst'">13.1</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'">21.0</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">10.0.17763.0</SupportedOSPlatformVersion>
		<TargetPlatformMinVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">10.0.17763.0</TargetPlatformMinVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'tizen'">6.5</SupportedOSPlatformVersion>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net8.0-android|AnyCPU'">
	  <AndroidPackageFormat>apk</AndroidPackageFormat>
	</PropertyGroup>

	<ItemGroup>
		<!-- App Icon -->
		<MauiIcon Include="Resources\AppIcon\appicon.svg">
			<Color>#FFF</Color>
			<BaseSize>32,32</BaseSize>
			<ForegroundScale>0.55</ForegroundScale>
		</MauiIcon>

		<MauiSplashScreen Include="Resources\Splash\maklsplash.svg" Color="#fff">

		</MauiSplashScreen>

		<!-- Splash Screen -->

		<!-- Images -->
		<MauiImage Include="Resources\Images\*" />
		<MauiImage Update="Resources\Images\dotnet_bot.svg" BaseSize="168,208" />

		<!-- Custom Fonts -->
		<MauiFont Include="Resources\Fonts\*" />

		<!-- Raw Assets (also remove the "Resources\Raw" prefix) -->
		<MauiAsset Include="Resources\Raw\**" LogicalName="%(RecursiveDir)%(Filename)%(Extension)" />
	</ItemGroup>
	
	<!--<ItemGroup>
		--><!-- App Icon --><!--
		<MauiIcon Include="Resources\AppIcon\appicon.svg" ForegroundFile="Resources\AppIcon\appiconfg.svg" Color="#512BD4" />

		--><!-- Splash Screen --><!--
		<MauiSplashScreen Include="Resources\Splash\splash.svg" Color="#512BD4" BaseSize="128,128" />

		--><!-- Images --><!--
		<MauiImage Include="Resources\Images\*" />
		<MauiImage Update="Resources\Images\dotnet_bot.png" Resize="True" BaseSize="300,185" />

		--><!-- Custom Fonts --><!--
		<MauiFont Include="Resources\Fonts\*" />

		--><!-- Raw Assets (also remove the "Resources\Raw" prefix) --><!--
		<MauiAsset Include="Resources\Raw\**" LogicalName="%(RecursiveDir)%(Filename)%(Extension)" />
	</ItemGroup>-->

	<ItemGroup>
	  <None Remove="Resources\Images\access_account.svg" />
	  <None Remove="Resources\Images\access_accounts.png" />
	  <None Remove="Resources\Images\back.png" />
	  <None Remove="Resources\Images\blog1.jpg" />
	  <None Remove="Resources\Images\blog2.jpg" />
	  <None Remove="Resources\Images\blog3.jpg" />
	  <None Remove="Resources\Images\blog4.jpg" />
	  <None Remove="Resources\Images\blog5.jpg" />
	  <None Remove="Resources\Images\blog6.jpg" />
	  <None Remove="Resources\Images\callback.svg" />
	  <None Remove="Resources\Images\check.png" />
	  <None Remove="Resources\Images\close.png" />
	  <None Remove="Resources\Images\consultation.jpg" />
	  <None Remove="Resources\Images\consultation1.jpg" />
	  <None Remove="Resources\Images\contactus.svg" />
	  <None Remove="Resources\Images\dental.jpg" />
	  <None Remove="Resources\Images\dental1.png" />
	  <None Remove="Resources\Images\dependants.svg" />
	  <None Remove="Resources\Images\downarrow.png" />
	  <None Remove="Resources\Images\empty.svg" />
	  <None Remove="Resources\Images\empty_pin.svg" />
	  <None Remove="Resources\Images\error_1.png" />
	  <None Remove="Resources\Images\error_2.png" />
	  <None Remove="Resources\Images\events.png" />
	  <None Remove="Resources\Images\exit.png" />
	  <None Remove="Resources\Images\faqs.svg" />
	  <None Remove="Resources\Images\female.png" />
	  <None Remove="Resources\Images\find_hospital.svg" />
	  <None Remove="Resources\Images\gps.png" />
	  <None Remove="Resources\Images\gradient1.png" />
	  <None Remove="Resources\Images\header1.jpeg" />
	  <None Remove="Resources\Images\header2.jpeg" />
	  <None Remove="Resources\Images\header3.jpeg" />
	  <None Remove="Resources\Images\header4.jpeg" />
	  <None Remove="Resources\Images\header5.jpeg" />
	  <None Remove="Resources\Images\hvisit.svg" />
	  <None Remove="Resources\Images\hypertension.png" />
	  <None Remove="Resources\Images\laboratory.jpg" />
	  <None Remove="Resources\Images\laboratory1.png" />
	  <None Remove="Resources\Images\lock.png" />
	  <None Remove="Resources\Images\logo.svg" />
	  <None Remove="Resources\Images\makllogo.png" />
	  <None Remove="Resources\Images\male.png" />
	  <None Remove="Resources\Images\medical_cover.svg" />
	  <None Remove="Resources\Images\mentalhealth.png" />
	  <None Remove="Resources\Images\menu.png" />
	  <None Remove="Resources\Images\offer.gif" />
	  <None Remove="Resources\Images\optical.jpg" />
	  <None Remove="Resources\Images\optical1.png" />
	  <None Remove="Resources\Images\password1.png" />
	  <None Remove="Resources\Images\password2.png" />
	  <None Remove="Resources\Images\password3.png" />
	  <None Remove="Resources\Images\pharmacy.jpg" />
	  <None Remove="Resources\Images\pharmacy1.png" />
	  <None Remove="Resources\Images\photoicon.png" />
	  <None Remove="Resources\Images\radiology.jpg" />
	  <None Remove="Resources\Images\remove.png" />
	  <None Remove="Resources\Images\reset.png" />
	  <None Remove="Resources\Images\search_1.png" />
	  <None Remove="Resources\Images\search_2.png" />
	  <None Remove="Resources\Images\search_3.png" />
	  <None Remove="Resources\Images\search_new.png" />
	  <None Remove="Resources\Images\settings.svg" />
	  <None Remove="Resources\Images\success.png" />
	  <None Remove="Resources\Images\tele_medicine.svg" />
	  <None Remove="Resources\Images\tips1.png" />
	  <None Remove="Resources\Images\tips2.png" />
	  <None Remove="Resources\Images\tips3.png" />
	  <None Remove="Resources\Images\ultrasound.jpg" />
	  <None Remove="Resources\Images\ultrasound1.png" />
	  <None Remove="Resources\Images\userprofilenew.png" />
	  <None Remove="Resources\Images\visits.svg" />
	  <None Remove="Resources\Images\visits2.svg" />
	  <None Remove="Resources\Images\vlogscover.png" />
	  <None Remove="Resources\Images\welcome.svg" />
	  <None Remove="Resources\Images\xray1.png" />
	  <None Remove="Resources\Images\x_ray.jpg" />
	</ItemGroup>

	<ItemGroup>
	  <None Include="..\.editorconfig" Link=".editorconfig" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="CommunityToolkit.Maui" Version="8.0.0" />
		<PackageReference Include="CommunityToolkit.Maui.MediaElement" Version="4.1.2" />
		<PackageReference Include="CommunityToolkit.Mvvm" Version="8.0.0" />
		<PackageReference Include="Microsoft.Maui.Controls" Version="8.0.91" />
		<PackageReference Include="Microsoft.Maui.Controls.Compatibility" Version="8.0.91" />
		<PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="8.0.0" />
		<PackageReference Include="Microsoft.Maui.Controls.Maps" Version="8.0.3" />
		<PackageReference Include="Microsoft.Maui.Maps" Version="8.0.3" />
		<PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
		<PackageReference Include="Syncfusion.Maui.Buttons" Version="24.1.41" />
		<PackageReference Include="Syncfusion.Maui.Calendar" Version="24.1.41" />
		<PackageReference Include="Syncfusion.Maui.Core" Version="24.1.41" />
		<PackageReference Include="Syncfusion.Maui.Inputs" Version="24.1.41" />
		<PackageReference Include="Xamarin.Essentials" Version="1.8.1" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\BlissApp.BLL\BlissApp.BLL.csproj" />
	  <ProjectReference Include="..\BlissApp.DTO\BlissApp.DTO.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <Compile Update="Pages\Dashboard\DawaPage.xaml.cs">
	    <DependentUpon>DawaPage.xaml</DependentUpon>
	  </Compile>
	  <Compile Update="Pages\Pharmacy\ClinicPage.xaml.cs">
	    <DependentUpon>ClinicPage.xaml</DependentUpon>
	  </Compile>
	  <Compile Update="Pages\Pharmacy\HospitalPage.xaml.cs">
	    <DependentUpon>HospitalPage.xaml</DependentUpon>
	  </Compile>
	  <Compile Update="Pages\Pharmacy\PrescriptionPage.xaml.cs">
	    <DependentUpon>PrescriptionPage.xaml</DependentUpon>
	  </Compile>
	</ItemGroup>

	<ItemGroup>
	  <MauiXaml Update="Controls\BannerTemplate.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Controls\ErrorMessage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Controls\FlyoutHeader.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Controls\InfoMessage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Controls\LargeTextLabel.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Controls\MedicineInfoPopUp.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Controls\OfferPopup.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Controls\SuccessMessage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Controls\SuccessPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Pages\Account\ChangePasswordPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Pages\Account\ChangePasswordPageTwo.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Pages\Account\DeleteAccountPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Pages\Account\ForgotPINPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Pages\Account\OTPLoginPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Pages\Account\OtpVerificationForgotPassword.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Pages\Account\OtpVerificationPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Pages\Account\OtpVerificationPageTwo.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Pages\Account\OTPVerifyEmailPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Pages\Account\ProfilePage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Pages\Account\RegisterPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Pages\Account\SendNewPinPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Pages\Account\SetPINPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Pages\Account\SignInPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Pages\Account\SignInPage2.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Pages\Account\SuccessfulPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Pages\Account\UploadProfilePicPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Pages\Account\WelcomePage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Pages\Appointment\AppointmentDetailsPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Pages\Appointment\AppointmentPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Pages\Blogs\BlogPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Pages\Blogs\NewPage1.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Pages\Blogs\VlogsPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Pages\Callback\CallbackDetailPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Pages\Callback\RequestCallbackPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Pages\ContactUs\ContactUsPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Pages\ContactUs\VideoPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Pages\Dashboard\DawaPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Pages\Dashboard\ConsultationPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Pages\Dashboard\DashboardPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Pages\Dashboard\DentalPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Pages\Dashboard\LaboratoryPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Pages\Dashboard\OpticalPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Pages\Dashboard\PharmacyPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Pages\Dashboard\Radiology.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Pages\Dashboard\UltrasoundPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Pages\Dashboard\XrayPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Pages\Dependants\DependantDetailPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Pages\Dependants\DependantPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Pages\Dependants\UploadEcardPhotoPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Pages\FamilyMember\AddMemberPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Pages\FamilyMember\EditMemberDetailsPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Pages\FamilyMember\FamilyDetailPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Pages\Feedback\FeedbackHistoryPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Pages\Feedback\FeedbackPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Pages\HospitalVisit\HospitalVisitPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Pages\MedicalCentres\CountiesPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Pages\MedicalCentres\MedicalCentreDetailsPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Pages\MedicalCentres\MedicalCentrePage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Pages\Offers\OfferPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Pages\Pharmacy\AddToCartPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Pages\Pharmacy\BookAppointmentPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Pages\Pharmacy\CartItemsPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Pages\Pharmacy\ClinicPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Pages\Pharmacy\HospitalPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Pages\Pharmacy\PrescriptionPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Pages\Pharmacy\OrderMedicinePage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Pages\Pharmacy\UploadPrescriptionPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Pages\Settings\SettingsPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Pages\Telemedicine\TelemedicinePage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Resources\Styles\ButtonStyles.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Resources\Styles\EntryStyles.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Resources\Styles\FrameStyles.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Resources\Styles\LabelStyles.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Resources\Styles\Onboarding.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	</ItemGroup>

</Project>
